searches:
  example:
    name: 'Long name for Example'
    index: 'logstash-24hours'
    query:
      bool:
        must:
          query_string:
            query: <query>
        filter:
          range:
            "@timestamp":
              gte: now-5m
              lte: now
