searches:
  example:
    name: 'Long name for Example'
    index: 'logstash-24hours'
    query:
      bool:
        filter:
        - query_string:
            analyze_wildcard: true
            query: <query>
          range:
            "@timestamp":
              gte: now-5m
              lte: now
              format: epoch_millis
